name: "Otus hw18"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clone_project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Run command on remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.PROJECT_FOLDER }}
            git checkout main
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d
            ls -la
