name: "Otus hw18"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clone_project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build_docker
        uses: ./
        with:
          compose-file: "./docker-compose.yml"
        env:
          APP_ENV: ${{ env.APP_ENV }}
