name: "Otus hw18"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clone_project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build_docker
        run: |
          touch .env
          echo "${{ env.APP_ENV }}" > .env
      - name: build docker
        run: docker-compose build
        
  remote_server:
      name: Run command on remote server
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{secrets.SSH_HOST}}
        user: ${{secrets.SSH_USER}}
        private_key: ${{secrets.SSH_PRIVATE_KEY}}
        command: |
          echo 'we are on the server'
